Run python -m pip install --upgrade pip
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.12.14/x64/lib/python3.12/site-packages (26.2.1)
Collecting fastapi==0.115.6 (from -r requirements.txt (line 1))
  Downloading fastapi-0.115.6-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn==0.34.0 (from uvicorn[standard]==0.34.0->-r requirements.txt (line 2))
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Collecting pydantic==2.10.5 (from -r requirements.txt (line 3))
  Downloading pydantic-2.10.5-py3-none-any.whl.metadata (30 kB)
Collecting pandas==2.2.3 (from -r requirements.txt (line 4))
  Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting numpy==2.2.1 (from -r requirements.txt (line 5))
  Downloading numpy-2.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting python-multipart==0.0.20 (from -r requirements.txt (line 6))
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Collecting scikit-learn==1.6.1 (from -r requirements.txt (line 7))
  Downloading scikit_learn-1.6.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting xgboost==2.1.3 (from -r requirements.txt (line 8))
  Downloading xgboost-2.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Collecting lightgbm==4.5.0 (from -r requirements.txt (line 9))
  Downloading lightgbm-4.5.0-py3-none-manylinux_2_28_x86_64.whl.metadata (17 kB)
Collecting shap==0.46.0 (from -r requirements.txt (line 10))
  Downloading shap-0.46.0-cp312-cp312-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (24 kB)
Collecting sqlalchemy==2.0.37 (from -r requirements.txt (line 11))
  Downloading SQLAlchemy-2.0.37-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting psycopg==3.2.3 (from psycopg[binary]==3.2.3->-r requirements.txt (line 12))
  Downloading psycopg-3.2.3-py3-none-any.whl.metadata (4.3 kB)
Collecting geoalchemy2==0.17.1 (from -r requirements.txt (line 13))
  Downloading GeoAlchemy2-0.17.1-py3-none-any.whl.metadata (2.3 kB)
Collecting redis==5.2.1 (from -r requirements.txt (line 14))
  Downloading redis-5.2.1-py3-none-any.whl.metadata (9.1 kB)
Collecting celery==5.4.0 (from -r requirements.txt (line 15))
  Downloading celery-5.4.0-py3-none-any.whl.metadata (21 kB)
Collecting pytest==8.3.4 (from -r requirements.txt (line 16))
  Downloading pytest-8.3.4-py3-none-any.whl.metadata (7.5 kB)
Collecting httpx==0.28.1 (from -r requirements.txt (line 17))
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting starlette<0.42.0,>=0.40.0 (from fastapi==0.115.6->-r requirements.txt (line 1))
  Downloading starlette-0.41.3-py3-none-any.whl.metadata (6.0 kB)
Collecting typing-extensions>=4.8.0 (from fastapi==0.115.6->-r requirements.txt (line 1))
2s
1s
1s
1m 48s
======================================================================
TRAINING: XGBoost
======================================================================
Training completed.
MAE  : 5.9537
RMSE : 9.1773
R²   : 0.9368
Training Time: 2.30 seconds
======================================================================
TRAINING: LightGBM
======================================================================
Training completed.
MAE  : 5.9311
RMSE : 9.1258
R²   : 0.9375
Training Time: 1.23 seconds
======================================================================
MODEL COMPARISON
======================================================================
        model      MAE     RMSE       R2  training_time_seconds
Random Forest 5.870003 8.289415 0.948402             100.602754
     LightGBM 5.931072 9.125787 0.937464               1.232374
      XGBoost 5.953696 9.177268 0.936757               2.298206
======================================================================
BEST MODEL
======================================================================
Model: Random Forest
MAE: 5.8700
RMSE: 8.2894
R²: 0.9484
Best model saved to:
data/models/best_pm25_model.joblib
Model feature list saved to:
data/models/model_features.csv
Model comparison saved to:
data/model_comparison.csv
Random Forest feature importance saved to:
data/random_forest_feature_importance.csv
XGBoost feature importance saved to:
data/xgboost_feature_importance.csv
LightGBM feature importance saved to:
data/lightgbm_feature_importance.csv
======================================================================
MODEL TRAINING AND SAVING COMPLETED SUCCESSFULLY
======================================================================
Selected model: Random Forest
Saved model: data/models/best_pm25_model.joblib
0s
Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
Post job cleanup.
(node:2279) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
0s
Node 20 is being deprecated. This workflow is running with Node 24 by default. If you need to temporarily use Node 20, you can set the ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true environment variable. For more information see: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
Post job cleanup.
/usr/bin/git version
git version 2.55.0
Temporarily overriding HOME='/home/runner/work/_temp/ea07a967-12a3-49a7-b7d9-7716d5da617e' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/india-air-pollution-intelligence-api/india-air-pollution-intelligence-api
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
/usr/bin/git config --local --name-only --get-regexp ^includeIf\.gitdir:
/usr/bin/git submodule foreach --recursive git config --local --show-origin --name-only --get-regexp remote.origin.url
